name: Run Python Scrapers

on:
  # 手動觸發
  workflow_dispatch:
  # 每天凌晨12點自動觸發
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    
    steps:
    # 檢出程式碼
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 設置 Python 環境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # 安裝依賴
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 執行 API 爬蟲
    - name: Run API Scraper
      run: python api.py

    # 執行靜態爬蟲
    - name: Run Static Scraper
      run: python static.py

      # 設定 Git
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'

    # 提交生成的檔案並推送到儲存庫
    - name: Commit and push the results
      run: |
        git add .
        git commit -m "Add API and Static Scraper results"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
